#============================================================================
#	Datei:		dockerfile
#
#	Summary:	Dieses Dockerfile fügt dem Standard wordpress Image wp-cli hinzu 
#
#	Datum:		2019-02-24
#
#	PowerShell Version: 5.1
#   Docker Version: 18.09.2
#------------------------------------------------------------------------------
#	Geschrieben von 
#       Dr. Benjamin Kettner, ML!PA Consulting GmbH 
#       Frank Geisler, GDS Business Intelligence GmbH
#
#   Dieses Script ist nur zu Lehr- bzw. Lernzwecken gedacht und wird im Buch
#   Docker für Dummies vorgestellt.
#  
#   DIESER CODE UND DIE ENTHALTENEN INFORMATIONEN WERDEN OHNE GEWÄHR JEGLICHER 
#   ART ZUR VERFÜGUNG GESTELLT, WEDER AUSDRÜCKLICH NOCH IMPLIZIT, EINSCHLIESSLICH, 
#   ABER NICHT BESCHRÄNKT AUF FUNKTIONALITÄT ODER EIGNUNG FÜR EINEN BESTIMMTEN 
#   ZWECK. SIE VERWENDEN DEN CODE AUF EIGENE GEFAHR.
#============================================================================*/
FROM wordpress:latest
MAINTAINER Frank Geisler <frank_geisler@geislers.net>

# Pakete installieren die man für wp-cli benötigt
RUN apt-get update && apt-get install -y sudo less my-sql-client && curl -o /bin/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

# Wrapper für wp-cli kopieren und die entsprechenden Ausführungsberechtigungen setzen
COPY wp /bin/wp
RUN chmod 755 /bin/wp-cli.phar /bin/wp && sed -i -e 's/\r$//' /bin/wp

# Installationsdateien aufräumen
RUN apt-get clean && rm -rf /var/lib/opt/lists/* /tmp/* /var/tmp/*